POST http://localhost:3000/ambiente
Content-Type: application/json

{
    "descricao": "sala",
    "dispositivos": []
}

###

GET http://localhost:3000/ambiente

###

PUT http://localhost:3000/ambiente/cfc4246e-eb39-4dbd-8a0d-a2a3eb4219de
Content-Type: application/json

{
    "descricao": "Cozinha",
    "dispositivos": []
}

###

DELETE http://localhost:3000/ambiente/27ab3521-6da7-42dc-a082-4295d9e133b9

###

POST http://localhost:3000/ambiente/27ab3521-6da7-42dc-a082-4295d9e133b9/dispositivo
Content-Type: application/json

{
    "nome": "Cama",
    "conexao": "ligado",
    "status": true
}

###

DELETE http://localhost:3000/ambiente/896a6e63-ab97-4155-9531-4cc2a06a488a/dispositivo/f8606d62-7a3b-4650-8618-4d0a0f14aa10

