POST http://localhost:3000/ambiente
Content-Type: application/json

{
    "descricao": "sala",
    "dispositivos": []
}

###

GET http://localhost:3000/ambiente

###

PUT http://localhost:3000/ambiente/e27cb4a5-8f1c-4eba-aa74-1d204587ceae
Content-Type: application/json

{
    "descricao": "Cozinha",
    "dispositivos": []
}

###

DELETE http://localhost:3000/ambiente/8866f245-ea54-42d2-825d-bb30ac6de74f

###

POST http://localhost:3000/ambiente/40fe77a6-133a-493c-a002-9eae32415dad/dispositivo
Content-Type: application/json

{
    "nome": "Cama",
    "conexao": "ligado",
    "status": true
}

###

DELETE http://localhost:3000/ambiente/7d59b0ce-491c-47e8-9589-c9211040b9e0/dispositivo/47ec71c7-459f-4c93-8105-48609e6554b7

