POST http://localhost:3000/pessoas
Content-Type: application/json

{
    "apelido": "ciclano",
    "nome": "Joao",
    "nascimento": "10/05/2000",
    "stack": ["java", "C#"]
}

###

GET http://localhost:3000/pessoas

###

PUT http://localhost:3000/pessoas/3811140a-fe6a-497b-b972-40cc9f230e3b
Content-Type: application/json

{
    "apelido": "ciclano",
    "nome": "Claudio",
    "nascimento": "12/05/2000",
    "stack": ["java", "C#"]
}

###

DELETE http://localhost:3000/pessoas/3811140a-fe6a-497b-b972-40cc9f230e3b

###

